---
# Vagrant hostname and IP configuration.
vagrant_hostname: local.cloudvm.com
vagrant_ip: 192.168.4.40

# A list of synced folders, with the keys 'local_path', 'destination', and 'id'.
# You can use NFS by switching the 'type' to 'nfs'.
vagrant_synced_folders:
  - local_path: ~/Sites/drupal
    destination: /drupal
    excluded_paths: [".git/"]
    id: drupal
    type: rsync

# Memory and CPU to use for this VM.
vagrant_memory: 1024
vagrant_cpus: 2

# Other variables in this file will be used during Ansible provisioning.
drush_version: "6.2.0"

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "8025"
  - "8983"

varnish_listen_port: 80
varnish_storage: "malloc,256m"

apache_listen_port: 8080
apache_vhosts:
  - servername: "local.cloudvm.com"
    documentroot: "/drupal"
  - servername: "local.xhprof.com"
    documentroot: "/usr/share/php/xhprof_html"

php_version: "5.3"
php_memory_limit: "256M"
php_display_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"

# APC will be enabled for PHP < 5.5, OpCache for PHP 5.5+.
php_apc_enabled_in_ini: true
php_apc_shm_size: "128M"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "128"
php_opcache_max_accelerated_files: 4096

# Disable main XDebug components unless needed.
php_xdebug_coverage_enable: 0
php_xdebug_default_enable: 0

mysql_root_password: root
mysql_databases:
  - name: cloudvm
    encoding: utf8
    collation: utf8_general_ci

solr_version: '3.6.2'
