---
- hosts: all

  vars_files:
    - config.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

    - name: Add ondrej repository for PHP 5.4.
      apt_repository: repo='ppa:ondrej/php5-oldstable'
      when: php_version == "5.4"

    - name: Add ondrej repository for PHP 5.5.
      apt_repository: repo='ppa:ondrej/php5'
      when: php_version == "5.5"

    - name: Add ondrej repository for PHP 5.6.
      apt_repository: repo='ppa:ondrej/php5-5.6'
      when: php_version == "5.6"

  roles:
    - { role: geerlingguy.firewall, tags: ['firewall'] }
    - { role: geerlingguy.git, tags: ['git'] }
    - { role: geerlingguy.apache, tags: ['apache'] }
    - { role: geerlingguy.mysql, tags: ['mysql'] }
    - { role: geerlingguy.varnish, tags: ['varnish'] }
    - { role: geerlingguy.memcached, tags: ['memcached'] }
    - { role: geerlingguy.php, tags: ['php'] }
    - { role: geerlingguy.php-pecl, tags: ['php'] }
    - { role: geerlingguy.php-mysql, tags: ['php'] }
    - { role: geerlingguy.php-memcached, tags: ['php'] }
    - { role: geerlingguy.php-xdebug, tags: ['php'] }
    - { role: geerlingguy.php-xhprof, tags: ['php'] }
    - { role: geerlingguy.phpmyadmin, tags: ['phpmyadmin'] }
    - { role: geerlingguy.composer, tags: ['composer'] }
    - { role: geerlingguy.drush, tags: ['drush'] }
    - { role: geerlingguy.daemonize, tags: ['mail'] }
    - { role: geerlingguy.mailhog, tags: ['mail'] }
    - { role: geerlingguy.java, tags: ['solr'] }
    - { role: geerlingguy.solr, tags: ['solr'] }

  tasks:
    - name: Remove default Apache virtualhost file.
      file:
        path: "{{ item }}"
        state: absent
      notify: restart webserver
      with_items:
        - /etc/apache2/sites-enabled/000-default
        - /etc/apache2/sites-enabled/000-default.conf

    - name: Ensure networking tools are installed.
      apt: "name={{ item }} state=installed"
      with_items:
        - curl
        - wget
        - iftop
        - traceroute
        - tcpdump

    - name: Ensure performance analysis tools are installed.
      apt: "name={{ item }} state=installed"
      with_items:
        - htop
        - iotop
        - sysstat # includes netstat
        - lsof
        - strace

    - name: Ensure other helpful software is installed.
      apt: "name={{ item }} state=installed"
      with_items:
        - imagemagick

    - name: Ensure development tools are installed.
      apt: "name={{ item }} state=installed"
      with_items:
        - vim
        - emacs
